version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/AliyunContainerService/alicloud-storage-provisioner
    steps:
    - checkout
    - run: go test ./...
    - run: cd build && sh build.sh
