kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: disk-efficiency
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-efficiency
  resources:
    requests:
      storage: 20Gi

---
kind: Pod
apiVersion: v1
metadata:
  name: disk-pod-efficiency
spec:
  containers:
  - name: disk-pod
    image: nginx
    volumeMounts:
      - name: disk-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: disk-pvc
      persistentVolumeClaim:
        claimName: disk-efficiency